# Generated by Django 2.1.3 on 2018-12-18 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestionGanancias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockInicial', models.IntegerField(null=True)),
                ('compras', models.IntegerField(null=True)),
                ('existenciaFinal', models.IntegerField(null=True)),
                ('costoFinal', models.FloatField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('costo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=60)),
                ('precioProducto', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProovedor', models.CharField(max_length=60)),
                ('descripcionProovedor', models.TextField(blank=True)),
                ('direccionProovedor', models.CharField(blank=True, max_length=60)),
                ('telefonoProovedor', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReposicion', models.DateField(default=datetime.date.today)),
                ('cantidadStock', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFlaming.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proovedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFlaming.Proovedor'),
        ),
        migrations.AddField(
            model_name='gestionganancias',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFlaming.Producto'),
        ),
    ]
