# Generated by Django 2.1.3 on 2018-12-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proovedor',
            name='telefonoProovedor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
