# Generated by Django 2.1.3 on 2018-12-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlaming', '0002_auto_20181218_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproducto',
            name='precioStock',
            field=models.FloatField(default=0),
        ),
    ]
